package grain:web@0.1.0;

interface dom {
  resource html-element {
    // Methods
    set-text: func(text: string);
  }
  // Methods
  create-paragraph: func(text: string) -> html-element;
  add-dom-node: func(parent: string, node: html-element);
  add: func(a: u32, b: u32) -> u32;
}

world web {
  import dom;
}