package spotandjake:grain-web@0.0.1;

interface web-interface {
  resource web-element {
    // Queries
    query: func(selector: string) -> option<web-element>;
    // Content
    get-text: func() -> option<string>;
    set-text: func(text: string) -> web-element;
    // Children
    // Debug
    print: func();
  }
  // queries
  query: func(selector: string) -> option<web-element>;
}

world grain-web {
  import web-interface;
}